apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clinic
  template:
    metadata:
      labels:
        app: clinic
    spec:
      containers:
        - name: clinic
          image: clinic:1.0 # o tu registry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: '3306'
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              value: genosentinel

---
apiVersion: v1
kind: Service
metadata:
  name: clinic
spec:
  selector:
    app: clinic
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP # ¡NO NodePort! solo auth se expone
