apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic
  template:
    metadata:
      labels:
        app: clinic
    spec:
      containers:
        - name: clinic
          image: clinic:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: clinic
spec:
  selector:
    app: clinic
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
